name: Showcase Tests
on:
  schedule:
    - cron: "0 0,12 * * *" # run twice daily
  push:
    branches:
      - master
    paths:
      - "showcases/"
  pull_request:
    branches:
      - "**"
    paths:
      - "showcases/"
  workflow_dispatch: {}
jobs:
  test:
    name: Run Compilation Check for Showcases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"
      - name: Run Showcase test with latest Legend versions
        run: |
          mvn versions:use-latest-versions -f showcases/pom.xml
          mvn -B -Dmaven.surefire.thread.count=$THREAD_COUNT -showcase.locations=$SHOWCASE_LOCATIONS test
        env:
          THREAD_COUNT: 3
          SHOWCASE_LOCATIONS: showcases/data
